Hw7
olgalupuleac/java_hw pull request #10
Opened 2017-11-15 12:14 UTC by olgalupuleac

2017-11-28 16:35 UTC, jzuken requested changes

2017-11-28 16:35 UTC, jzuken commented on hw7/src/main/java/ru/spbau202/lupuleac/TreeSet/TreeSet.java
> +public class TreeSet<E> extends AbstractSet<E> implements MyTreeSet<E> {
тут бы не помешали подходящие wildcard'ы у генериков

2017-11-28 16:35 UTC, jzuken commented on hw7/src/main/java/ru/spbau202/lupuleac/TreeSet/TreeSet.java
> +    private TreeSet<E> left;
давайте разделим сущности множества и дерева, которое оно используется для работы

2017-11-28 16:35 UTC, jzuken commented on hw7/src/main/java/ru/spbau202/lupuleac/TreeSet/TreeSet.java
> +    public E lower(@NotNull E e) {
а код этого метода никак нельзя объединить с кодом floor()? практически одно и тоже же

2017-11-28 16:35 UTC, jzuken commented on hw7/src/main/java/ru/spbau202/lupuleac/TreeSet/TreeSet.java
> +    public boolean remove(@NotNull Object e) {
лучше бы выделить вспомогательные методы тут

2017-11-28 16:35 UTC, jzuken commented on hw7/src/main/java/ru/spbau202/lupuleac/TreeSet/TreeSet.java
> +        public E next() {
а тут всякие методы типа lower() не заиспользовать?

2017-12-03 16:51 UTC, olgalupuleac commented on hw7/src/main/java/ru/spbau202/lupuleac/TreeSet/TreeSet.java
> +    private TreeSet<E> left;
Имеется в виду, что нельзя хранить ссылку на дерево в дереве? Но это же достаточно удобно. У нас используются все методы из дерева, даже итератор, когда мы хотим найти самый маленький элемент в правом поддереве. И мы можем всегда определить, что данное дерево является корнем, так как у него parent null.

2017-12-04 07:10 UTC, jzuken commented on hw7/src/main/java/ru/spbau202/lupuleac/TreeSet/TreeSet.java
> +    private TreeSet<E> left;
нет, имеется в виду, сделать два разных класса -- дерево и множество. второе будет композировать первое и перенаправлять ему запросы по необходимости для операций с данными

2017-12-05 09:08 UTC, olgalupuleac commented on hw7/src/main/java/ru/spbau202/lupuleac/TreeSet/TreeSet.java
> +public class TreeSet<E> extends AbstractSet<E> implements MyTreeSet<E> {
Я не понимаю, какие, вроде в исходниках настоящего TreeSet всё примерно так же, как у меня.
http://grepcode.com/file_/repository.grepcode.com/java/root/jdk/openjdk/6-b27/java/util/TreeSet.java/?v=source

2017-12-05 09:33 UTC, jzuken commented on hw7/src/main/java/ru/spbau202/lupuleac/TreeSet/TreeSet.java
> +public class TreeSet<E> extends AbstractSet<E> implements MyTreeSet<E> {
ну ладно, пусть так останется

2017-12-20 15:11 UTC, jzuken requested changes

2017-12-20 15:11 UTC, jzuken commented on hw7/src/main/java/ru/spbau202/lupuleac/TreeSet/TreeSet.java
> +    private static class Tree<E> extends AbstractSet<E> implements MyTreeSet<E> {
а в отдельный файл его не вынесли потому что иначе бы тоже тестировать пришлось? ну ладно

2017-12-20 15:11 UTC, jzuken commented on hw7/src/main/java/ru/spbau202/lupuleac/TreeSet/TreeSet.java
> +            comparator = (Comparator<E>) (e1, e2) -> ((Comparable<E>) e1).compareTo(e2);
это бы логичнее сделать во множестве, а сюда уже просто передавать готовый компаратор всегда

2017-12-20 20:17 UTC, olgalupuleac commented on hw7/src/main/java/ru/spbau202/lupuleac/TreeSet/TreeSet.java
> +    private static class Tree<E> extends AbstractSet<E> implements MyTreeSet<E> {
Это значит, что можно оставить так :)?

2017-12-21 04:26 UTC, jzuken commented on hw7/src/main/java/ru/spbau202/lupuleac/TreeSet/TreeSet.java
> +    private static class Tree<E> extends AbstractSet<E> implements MyTreeSet<E> {
можно

2017-12-26 10:00 UTC, merged