T2.hw2
olgalupuleac/java_hw pull request #18
Opened 2018-03-23 05:57 UTC by olgalupuleac

2018-04-02 10:46 UTC, jzuken requested changes

2018-04-02 10:46 UTC, jzuken commented on term2/hw2/src/main/java/ru/spbau202/lupuleac/TicTacToe/Logic/Board.java
> +package ru.spbau202.lupuleac.TicTacToe.Logic;
названия пакетов обычно пишутся строчными буквами всегда

2018-04-02 10:46 UTC, jzuken commented on term2/hw2/settings.gradle
> +rootProject.name = 'TicTacToe'
а чего кнопки как странно выровнены на первом экране? сделайте их уж одного размера.
и было бы здорово, чтобы экран нельзя было бы зазумить слишком мелко

2018-04-02 10:46 UTC, jzuken commented on term2/hw2/settings.gradle
> +rootProject.name = 'TicTacToe'
почему кнопка на странице статистики называется restart? и хочется, чтобы не появлялось новых окон, а всё было в одном окне. и размер бы не прыгал при переходе между окнами

2018-04-02 10:46 UTC, jzuken commented on term2/hw2/settings.gradle
> +rootProject.name = 'TicTacToe'
статистику хочется по каждому режиму отдельно

2018-04-25 10:49 UTC, jzuken commented
окошко из начального размера всё равно зумится крайне некрасиво

2018-04-25 10:50 UTC, jzuken commented
ну и нотификацию о победе хорошо бы сделать по-удобнее, хотя бы кнопку "ок" туда добавить. а то просто показывает окошко с текстом и всё

2018-04-25 10:55 UTC, jzuken requested changes

2018-04-25 10:55 UTC, jzuken commented on term2/hw2/src/main/java/ru/spbau202/lupuleac/ticTacToe/Settings.java
> +package ru.spbau202.lupuleac.ticTacToe;
не, оно _всё_ пишется в нижнем регистре: http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-135099.html#367

2018-05-14 08:49 UTC, jzuken commented
теперь оно за правый нижний край зумится так:
![image](https://user-images.githubusercontent.com/705678/39987220-c84ba638-576c-11e8-9e03-d46e2d8daa74.png)
вы хоть сами то попробуйте с размером поиграться

2018-05-23 11:50 UTC, olgalupuleac commented
Сейчас оно вроде зумится, но выглядит достаточно смешно.

2018-06-14 07:21 UTC, jzuken commented
ну блин. а можно, чтобы кнопки зумились вместе с окном пропорционально?
![image](https://user-images.githubusercontent.com/705678/41397382-b8c81846-6fbc-11e8-9520-27266d80892e.png)

2018-06-20 06:55 UTC, merged