Hw5 1
olgalupuleac/java_hw pull request #7
Opened 2017-10-18 19:45 UTC by olgalupuleac

2017-11-05 15:22 UTC, jzuken requested changes

2017-11-05 15:22 UTC, jzuken commented on .gitignore
> +
на этом файле конфликт с мастером, хорошо бы смерджить сюда изменения оттуда и поправить конфликт

2017-11-05 15:22 UTC, jzuken commented on hw5.1/build.gradle
> +    testCompile group: 'junit', name: 'junit', version: '4.12'
а ещё грэдлу надо сказать про пакет с аннотациями, а то в консоли он это не соберёт. 
-1

2017-11-05 15:22 UTC, jzuken commented on hw5.1/src/main/java/ru/spbau202/lupuleac/Maybe/AccessToNothingException.java
> +public class AccessToNothingException extends RuntimeException {
а есть какая-то веская причина, почему оно RuntimeException?

2017-11-05 15:22 UTC, jzuken commented on hw5.1/src/main/java/ru/spbau202/lupuleac/Main.java
> +import com.sun.istack.internal.NotNull;
вообще я рассказывал про org.jetbrains.annotations.NotNull

2017-11-05 15:22 UTC, jzuken commented on hw5.1/src/main/java/ru/spbau202/lupuleac/Maybe/Maybe.java
> +    public Maybe(@Nullable T t) {
конструкторы должны быть закрытые, иначе весь смысл методов just() и nothing() пропадает

2017-11-05 15:22 UTC, jzuken commented on hw5.1/src/main/java/ru/spbau202/lupuleac/Maybe/Maybe.java
> +    public Maybe(@Nullable T t) {
и да, давайте тут тоже NotNull поставляем в нужных местах

2017-11-05 15:22 UTC, jzuken commented on hw5.1/src/main/java/ru/spbau202/lupuleac/Maybe/Maybe.java
> +            return new Maybe<>();
а тут зачем новый объект создавать?

2017-11-13 16:54 UTC, olgalupuleac commented on hw5.1/src/main/java/ru/spbau202/lupuleac/Maybe/AccessToNothingException.java
> +public class AccessToNothingException extends RuntimeException {
Да, так как тогда не надо его будет каждый раз специально обрабатывать, а можно просто проверть, что объект не Nothing

2017-11-17 04:18 UTC, jzuken commented on hw5.1/src/main/java/ru/spbau202/lupuleac/Maybe/AccessToNothingException.java
> +public class AccessToNothingException extends RuntimeException {
просто проблема в том, что это исключение будет прятаться во всех сигнатурах методов, его бросающих. из-за небольшого удобства вам пропадает документирующая функция исключений. в вобщем, без серьёзной причины (например, невозможность изменить секцию throws у опубликованного метода) непроверяемые исключения создавать не рекомендуется

2017-11-26 17:31 UTC, jzuken requested changes

2017-11-26 17:31 UTC, jzuken commented on hw5.1/src/main/java/ru/spbau202/lupuleac/Maybe/Maybe.java
> +            return nothing();
от того, что вы вызвали метод вместо явного new, объект не перестал создаваться. я имел в виду, что тут вполне можно this вернуть

2017-11-27 09:28 UTC, olgalupuleac commented on hw5.1/src/main/java/ru/spbau202/lupuleac/Maybe/Maybe.java
> +            return nothing();
Нет, не могу, так как this типа Maybe<T>, а ответ типа Maybe<U>. По крайней мере, у меня в idea подчёркивается красным.

2017-11-27 11:35 UTC, jzuken commented on hw5.1/src/main/java/ru/spbau202/lupuleac/Maybe/Maybe.java
> +            return nothing();
ах, да. ну ладно

2017-11-27 11:35 UTC, merged